# Generated by Django 5.0.6 on 2024-06-06 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accuknox_app', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='FriendRequestModel',
        ),
    ]
